import numpy as np
from datasets import load_dataset
import pandas as pd

# 1. Load the scores generated by the pipeline
print("[analyze] Loading curriculum_scores.npy...")
scores = np.load("curriculum_scores.npy")

difficulties = scores[:, 1]
ppls = scores[:, 2]
ttrs = scores[:, 3]
lengths = scores[:, 4]

# 2. Print Distribution Statistics
print("\n" + "="*50)
print("  DIFFICULTY SCORE DISTRIBUTION")
print("="*50)
df = pd.DataFrame({"Difficulty": difficulties, "PPL": ppls, "TTR": ttrs, "Length": lengths})
print(df.describe(percentiles=[0.05, 0.25, 0.50, 0.75, 0.95]).to_string())

# 3. Verify if scores are collapsed or properly distributed
std_dev = np.std(difficulties)
spread = np.max(difficulties) - np.min(difficulties)

print("\n" + "="*50)
print("  COLLAPSE ANALYSIS VERDICT")
print("="*50)
if std_dev < 0.5:
    print(f"⚠️ DANGER: Scores are highly collapsed! Std-Dev is only {std_dev:.2f}")
elif std_dev >= 0.5 and spread > 5.0:
    print(f"✅ HEALTHY: The composite algorithm perfectly segmented the data! (Std Dev: {std_dev:.2f}, Spread: {spread:.2f})")

# 4. Fetch Text Samples (Non-Streaming to bypass network hangs)
print("\n" + "="*50)
print("  FETCHING O(1) GROUND TRUTH SAMPLES")
print("="*50)
print("[analyze] Downloading/Loading Miniature TinyStories Subset to RAM...")
ds = load_dataset("roneneldan/TinyStories", split="train[:20000]")

# Filter scores to only include those where original_idx < 20000
valid_scores = scores[scores[:, 0] < 20000]

def get_percentile_row(percentile):
    idx = int(len(valid_scores) * percentile)
    row = valid_scores[idx]
    orig_idx = int(row[0])
    text = ds[orig_idx]["text"].replace("\n", " ")
    if len(text) > 350:
         text = text[:350] + "..."
    return row, orig_idx, text

tiers = {
    "SUPER EASY (5th Percentile)": 0.05,
    "EASY/MEDIUM (25th Percentile)": 0.25,
    "MEDIUM (50th Percentile)": 0.50,
    "HARD (75th Percentile)": 0.75,
    "EXTREME (95th Percentile)": 0.95
}

for label, pct in tiers.items():
    row, orig_idx, text = get_percentile_row(pct)
    print(f"\n{label}:")
    print(f"  Score: {row[1]:.2f}  |  PPL: {row[2]:.2f}  |  TTR: {row[3]:.2f}  |  Length: {row[4]:.0f}")
    print(f"  Text [{orig_idx}]: \"{text}\"")
